// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2538.RecycleRush2538.subsystems;

import org.usfirst.frc2538.RecycleRush2538.RobotMap;
import org.usfirst.frc2538.RecycleRush2538.commands.*;

import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class PowerDistributionBoard extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	PowerDistributionPanel pdBoard = RobotMap.pdBoard;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new DisplayCAN());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void displayPDBoard() {
    	double leftFrontWheelPD = pdBoard.getCurrent(14);
    	double leftRearWheelPD = pdBoard.getCurrent(15);
    	double rightFrontWheelPD = pdBoard.getCurrent(3);
    	double rightRearWheelPD = pdBoard.getCurrent(2);
    	
    	double leftIntakeWheelPD = pdBoard.getCurrent(13);
    	double rightIntakeWheelPD = pdBoard.getCurrent(0);
    	
    	/*SmartDashboard.putNumber("Left Front Wheel Current", leftFrontWheelPD);
    	SmartDashboard.putNumber("Left Rear Wheel Current", leftRearWheelPD);
    	SmartDashboard.putNumber("Right Front Wheel Current", rightFrontWheelPD);
    	SmartDashboard.putNumber("Right Rear Wheel Current", rightRearWheelPD);
    	
    	SmartDashboard.putNumber("Left Intake Wheel Current", leftIntakeWheelPD);
    	SmartDashboard.putNumber("Right Intake Wheel Current", rightIntakeWheelPD);
    	*/		
    }
}

