// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2538.RecycleRush2538.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class StackThing extends CommandGroup {
    
    public  StackThing() {
    	addSequential(new ClosedConfigCommand());
    	addSequential(new intakeCommand());
    	addSequential(new ContainerConfigCommand());
    	addSequential(new LowerLift());
    	addSequential(new ExtendTridentCommand());
    	addSequential(new ClosedConfigCommand());
    	addSequential(new intakeCommand());
    	addSequential(new OpenConfigCommand());
    	addSequential(new RaiseLift());
    	addSequential(new Wait(), .15);
    	addSequential(new RetractTridentCommand());
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    }
}
